apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config
  namespace: custom-namespace
data:
  init.sql: |
    CREATE DATABASE users;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-datasource-url-config
  namespace: custom-namespace
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/users
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-db-config
  namespace: custom-namespace
data:
  init.sql: |
    CREATE DATABASE posts;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-datasource-url-config
  namespace: custom-namespace
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql1:5431/posts
  USER_SERVICE_HOST: http://user-service:8080