apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/user"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
