apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: custom-namespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: custom-namespace
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
